services:
  app:
    build:
      context: .
    environment:
      MONGO_HOSTBASE: ${MONGO_HOSTBASE:-host.docker.internal:27017}
      MONGO_USERNAME: ${MONGO_USERNAME:-root}
      MONGO_PASSWORD: ${MONGO_PASSWORD:-password}
      NODE_STREAM_URL: ${NODE_STREAM_URL:-qav2node.pbapp.net}
    volumes:
      - .:/var/www/control

  server:
    image: nginx:1.27.2-bookworm
    volumes:
      - ./scripts/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:80
    restart: always
